Ability to print constraints in search mode
kframework/k-legacy pull request #2210
Opened 2016-10-03 22:00 UTC by msaxena2

Opened PR from branch in the main repo to enable quicker building. Carried forward from #2209 .

2016-10-04 14:48 UTC, cos commented
you can update the outputs with `--update-out`

2016-10-04 21:32 UTC, msaxena2 commented
@cos @ehildenb @lucaspena Please review. Also, the constraints are now only printed when search is called with the --print-constraints flag.

2016-10-05 18:44 UTC, ehildenb commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/InitializeRewriter.java
> +import java.util.Set;
@msaxena2 It builds fine on my system without the extra import statements.

2016-10-07 14:43 UTC, cos requested changes
There are two main changes:
1. replace the Tuple2 with a conjunction
2. if there is no reason to keep it, remove the `--print-constraint` flag and have it always on

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/InitializeRewriter.java
> +        public List<Tuple2<? extends Map<? extends KVariable, ? extends K>, ? extends K>> match(K k, org.kframework.definition.Rule rule) {
it may not be clear what the second projection of the tuple is. a new class holding the map and the remaining constraints, or some javadoc to this method would help.

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/InitializeRewriter.java
> +        public List<Tuple2<? extends Map<? extends KVariable, ? extends K>, ? extends K>> search(K initialConfiguration, Optional<Integer> depth, Optional<Integer> bound, Rule pattern, SearchType sea
same, class or javadoc

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/InitializeRewriter.java
> +        public Tuple2<RewriterResult, List<Tuple2<? extends Map<? extends KVariable, ? extends K>, ? extends K>>> executeAndMatch(K k, Optional<Integer> depth, Rule rule) {
same, class or javadoc.

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +            HashSet<Tuple2<Substitution<Variable, Term>, K>> searchResults,
same as above, class or javadoc

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +    public Set<Tuple2<Substitution<Variable, Term>, K>> search(
same as above, class or javadoc

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +    public Set<Tuple2<Substitution<Variable, Term>, K>> search(
also, the javadoc seems to be obsolete -- might help to update it anyhow

2016-10-07 14:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +        HashSet<Tuple2<Substitution<Variable, Term>, K>> searchResults = Sets.newHashSet();
same

2016-10-07 14:43 UTC, cos commented on kernel/src/main/java/org/kframework/debugger/DebuggerMatchResult.java
> +    private final List<Tuple2<? extends Map<? extends KVariable, ? extends K>, ? extends K>>  substitutions;
same -- it looks like a separate class would be the best choice. as we want to work with K conjunctions in the future, it may be best to use that already, and document the methods.

2016-10-07 14:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        result.getSearchList().forEach(tuple -> {
"tuple" is not informative

2016-10-07 14:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        List<Tuple2<String, String>> results = new ArrayList<>();
what's the first and the second string?

2016-10-07 14:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRunOptions.java
> +    public boolean printConstraint = false;
if there is no other problem, let's always print the constraints (unless they are simply true)

2016-10-07 14:43 UTC, cos commented on kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> +  def `match`(k: kore.K, rule: Rule): java.util.List[Tuple2[_ <: java.util.Map[_ <: kore.KVariable, _ <: kore.K], _ <: kore.K]]
again, considering that this is the K API, we really should go with the conjunction. I know we discussed this before, but I didn't realize that the tuple will be leaking all the way to the API.

2016-10-07 14:43 UTC, cos commented on kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> +  def search(initialConfiguration: kore.K, depth: Optional[Integer], bound: Optional[Integer], pattern: Rule, searchType: SearchType): java.util.List[Tuple2[_ <: java.util.Map[_ <: kore.KVariable, _
same

2016-10-07 14:43 UTC, cos commented on kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> +  def executeAndMatch(k: kore.K, depth: Optional[Integer], rule: Rule): Tuple2[RewriterResult, java.util.List[Tuple2[_ <: java.util.Map[_ <: kore.KVariable, _ <: kore.K], _ <: kore.K]]]
same

2016-10-11 00:08 UTC, msaxena2 commented on kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> +  def `match`(k: kore.K, rule: Rule): java.util.List[Tuple2[_ <: java.util.Map[_ <: kore.KVariable, _ <: kore.K], _ <: kore.K]]
I agree that a conjunction should be the way to go. The rewriter returns a list of maps, where each map represents a substitution. I'm not sure how we can go from a list of maps to a conjunction, unless we make the rewriter itself return the map as a K term (which can then be used in a conjunction with the constraint). @cos  is that what you had in mind as well?

2016-10-11 00:45 UTC, andreistefanescu commented
The list of conjunctions can be represented by a disjunction.

On Mon, Oct 10, 2016, 5:08 PM Manasvi Saxena <notifications@github.com>
wrote:

> *@msaxena2* commented on this pull request.
> ------------------------------
>
> In kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> <https://github.com/kframework/k/pull/2210>:
>
> > @@ -23,7 +23,7 @@ trait Rewriter {
>    def execute(k: kore.K, depth: Optional[Integer]): RewriterResult
>
>
> -  def `match`(k: kore.K, rule: Rule): java.util.List[_ <: java.util.Map[_ <: kore.KVariable, _ <: kore.K]]
> +  def `match`(k: kore.K, rule: Rule): java.util.List[Tuple2[_ <: java.util.Map[_ <: kore.KVariable, _ <: kore.K], _ <: kore.K]]
>
> I agree that a conjunction should be the way to go. The rewriter returns a
> list of maps, where each map represents a substitution. I'm not sure how we
> can go from a list of maps to a conjunction, unless we make the rewriter
> itself return the map as a K term (which can then be used in a conjunction
> with the constraint). Is that what you had in mind as well?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kframework/k/pull/2210>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE3jMcWf806yDZeU58AWvMD09rXnOnAHks5qytNugaJpZM4KNFzP>
> .
>

2016-10-11 04:17 UTC, cos commented on kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> +  def `match`(k: kore.K, rule: Rule): java.util.List[Tuple2[_ <: java.util.Map[_ <: kore.KVariable, _ <: kore.K], _ <: kore.K]]
Yes. As @andreistefanescu said below, you want a disjunction of conjunctions. Each map becomes a conjunction, and the list becomes a disjunction.

2016-11-01 21:03 UTC, msaxena2 commented
@cos Please have a look.

2016-11-02 19:43 UTC, cos requested changes

2016-11-02 19:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/InitializeRewriter.java
> +        public K search(K initialConfiguration, Optional<Integer> depth, Optional<Integer> bound, Rule pattern, SearchType searchType, boolean substitution) {
rename `substitution` to something line `resultsAsSubstitutions`

2016-11-02 19:43 UTC, cos commented on k-distribution/tests/examples/symbolic/1.a.out
> + _andBool_ V0 ==K 0
this should be the ML conjunction, not the bool one

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        Set<String> patternVariables = new HashSet<>();
`patternVariables` => `patternVariableNames`

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +            Some<Tuple2<KLabel, scala.collection.immutable.List<K>>> searchResults = KApply$.MODULE$.unapply((KApply) result);
very involved. as we're in Java, simply cast to `KApply` and get its `KLabel` and `KList`, or I think it also works do to directly `items()` on it

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +            scala.collection.Seq<K> seq = Assoc.flatten(KORE.KLabel(KLabels.OR), searchResults.get()._2(), KORE.KLabel(KLabels.ML_FALSE));
this should us the ML disjunction

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        if (result instanceof KApply && ((KApply) result).klabel().equals(KLabel(KLabels.OR))) {
ML `or`

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +            List<K> resultList = mutable(seq).stream().filter(x -> !x.getClass().toString().contains("BoolToken")).collect(Collectors.toList());
do we end up with `true` and `false` bool tokens in the result? we shouldn't, for multiple reasons.

first, (unless they really are the final result of the computation; not the case ever in our examples) bool stuff should not appear in the disjunction directly. it should be `theBoolStuff ==K true`.

second, if talking about ML top and bottom (as opposed to true/false) we should either see just top, or a disjunction that has no bottom (normalized)

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +    public static int getExitCode(KExceptionManager kem, K res) {
what is this "exitCode"?

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        if (result instanceof KApply && ((KApply) result).klabel().toString().equals(KLabels.AND)) {
do not check string-based equality

2016-11-02 19:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +            if (x instanceof KItem && ((KItem) x).klabel().toString().equals(KLabels.AND)) {
do not check equality based on `toString`

2016-11-02 19:43 UTC, cos commented on java-backend/src/main/java/org/kframework/backend/java/symbolic/SymbolicRewriter.java
> +        if (conjunct.klabel().toString().equals(KLabels.AND)) {
same, `toString`

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +                if ((options.pattern != null) && x instanceof KApply && ((KApply) x).klabel().toString().equals(KLabels.EQUALS)) {
`toString`

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +                if (x.getClass().toString().contains("BoolToken")) {
don't use a string for the check

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +    private StringBuilder filterAnonVarsAndPrint(K result, Set<String> filterSet, CompiledDefinition compiledDef, KRunOptions options) {
if possible, separate the filter from the print

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        new VisitK() {
extract visitor to someplace else

2016-11-02 19:43 UTC, cos commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +            new VisitK() {
separate visitor -- this method is kind of large

2016-11-02 19:43 UTC, cos commented on kore/src/main/scala/org/kframework/rewriter/Rewriter.scala
> +  def search(initialConfiguration: kore.K, depth: Optional[Integer], bound: Optional[Integer], pattern: Rule, searchType: SearchType, subsitution:Boolean): kore.K
I really don't like how this method behaves differently based on the substitution flag. Let's leave it like this for now so we can merge, but please add an issue and we should fix this with the very first opportunity.

2016-11-08 16:43 UTC, msaxena2 commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +    public static int getExitCode(KExceptionManager kem, K res) {
Already existing code, seems like it matches some pre-existing pattern on the final configuration. Should probably get rid of it in a separate PR.

2016-11-08 16:44 UTC, msaxena2 commented on kernel/src/main/java/org/kframework/krun/KRun.java
> +        new VisitK() {
Let's let this be as is for now. We'll probably get rid of this function in a later PR.

2016-11-08 16:51 UTC, msaxena2 commented
@cos Please re-review.

2016-11-08 22:00 UTC, cos approved these changes

2016-11-08 22:01 UTC, merged