add more symbolic tests
kframework/k-legacy pull request #2228
Opened 2016-10-24 04:09 UTC by daejunpark

@cos please review. just added more tests.

2016-10-31 19:54 UTC, cos requested changes
looks good overall; I mostly just mirrored your own TODOs

2016-10-31 19:54 UTC, cos commented on API/src/main/java/org/kframework/Kapi.java
> +    public static void kequiv(CompiledDefinition compiledDef0, CompiledDefinition compiledDef1, CompiledDefinition compiledDef2, String proofFile1, String proofFile2, String prelude) {
rename  var names to match their function, e.g., `compiledDef0` => `parsingSpecDef`

2016-10-31 19:54 UTC, cos commented on API/src/main/java/org/kframework/Kapi.java
> +    // TODO: better name
rename

2016-10-31 19:54 UTC, cos commented on API/src/main/java/org/kframework/Kapi.java
> +    // TODO: better name
rename

2016-10-31 19:54 UTC, cos commented on kernel/src/main/java/org/kframework/keq/KeqOptions.java
> +    @Parameter(names="--def0", description="K kompiled definition of common language.")
the parameter names could be better

2017-02-06 03:33 UTC, daejunpark commented
Close deferred PR. Labeled with `deferred` for later search purpose.

2017-02-06 03:33 UTC, closed without merging