refactoring/clean up module transformers
kframework/k-legacy pull request #2229
Opened 2016-10-30 00:20 UTC by cos

Main changes:
 - removed the use of "hybrid" from all but the front-end code
 - most transformers now inherit from ModuleTransformer, which takes care of correct recursive application

2016-11-02 20:21 UTC, cos commented
@daejunpark, please review

2016-11-02 22:48 UTC, cos commented
@daejunpark is at OOPSLA. anyone else, please feel free to pick this up.

2016-11-03 14:02 UTC, radumereuta requested changes
Overall looks as the code became a bit more readable, although it needs a bit more comments.

2016-11-03 14:02 UTC, radumereuta commented on k-distribution/src/test/java/org/kframework/kore/convertors/BubbleParsing.java
>       * TODO(radu): generalize this function, and eliminate duplicates
Is this comment still valid?

2016-11-03 14:02 UTC, radumereuta commented on kernel/src/main/java/org/kframework/kore/compile/ResolveAnonVar.java
> +    public synchronized Sentence f(Sentence s) {
This should have a better name. At least JavaDoc.

2016-11-03 14:02 UTC, radumereuta commented on kernel/src/main/java/org/kframework/kore/compile/ResolveHeatCoolAttribute.java
> +    public Sentence f(Sentence s) {
Again, better name/JavaDoc, since it's public.

2016-11-03 14:02 UTC, radumereuta commented on kernel/src/main/java/org/kframework/kore/compile/ResolveSemanticCasts.java
> +    public synchronized Sentence f(Sentence s) {
dito

2016-11-03 14:02 UTC, radumereuta commented on kore/src/main/scala/org/kframework/definition/transformers.scala
> +abstract class SentenceBasedModuleTransformer extends BasicModuleTransformer {
Ah, this is where they come from.
This should have some JavaDoc. Maybe you can skip the previous ones if this class becomes easy to understand.

2016-11-03 14:11 UTC, cos commented on k-distribution/src/test/java/org/kframework/kore/convertors/BubbleParsing.java
>       * TODO(radu): generalize this function, and eliminate duplicates
no, it looks like you already made it nicer at some point.

one thing that could be done here is have the class implement `SentenceBasedModuleTransformer` instead of `BasicModuleTransformer`. The body of the map would become the implementation of `f` and the rest of the code in this function would go away.

2016-11-03 14:12 UTC, cos commented on k-distribution/src/test/java/org/kframework/kore/convertors/BubbleParsing.java
>       * TODO(radu): generalize this function, and eliminate duplicates
no, it looks like you already made it nicer at some point.

one thing that could be done here is have the class implement `SentenceBasedModuleTransformer` instead of `BasicModuleTransformer`. The body of the map would become the implementation of `f` and the rest of the code in this function would go away.

2016-11-03 14:21 UTC, cos commented
@radumereuta, I addressed all your comments.

The only place with remaining "hybrid" transformers is the frontend. Would you have time to have a go at removing them from there as well at some point? Or we could work together on it if you like.

2016-11-04 20:27 UTC, radumereuta commented
lgtm

2016-11-04 20:27 UTC, radumereuta approved these changes

2016-11-04 20:28 UTC, merged