fix the bug #2213 and #2057, for bug 2057, it will not  appear on Uba…
kframework/k-legacy pull request #2233
Opened 2016-11-27 21:25 UTC by JoeSun940303

…ntu VM but will appear on OSX or windows system. We add [read] after rule <k> read and change and change _ to AEs:AExps so that the print can be flushed out both in OSX system and windows system

2016-12-09 17:09 UTC, cos requested changes

2016-12-09 17:09 UTC, cos commented on k-distribution/src/test/java/org/kframework/krun/FlushTest.java
> +    public void formatTest() throws IOException {
what does this test?

2016-12-09 17:09 UTC, cos commented on k-distribution/src/test/java/org/kframework/kompile/KompileTest.java
> +    public void KompileTest() throws URISyntaxException, IOException, KEMException {
what does this test? please add javadoc

2016-12-09 17:09 UTC, cos commented on k-distribution/src/test/resources/convertor-tests/PrintFlushTest.k
> +module IMP
Is this the copy-pasted from another place? If so, just refer to that file.

2016-12-09 17:09 UTC, cos commented on k-distribution/tutorial/1_k/4_imp++/lesson_4/imp.k
> +                > Stmt Stmt                  [left]
please do not reformat the files if not necessary -- it makes reviewing much harder and breaks file change history

2016-12-11 02:01 UTC, JoeSun940303 commented on k-distribution/src/test/java/org/kframework/kompile/KompileTest.java
> +    public void KompileTest() throws URISyntaxException, IOException, KEMException {
Sorry about the confusion, just add javadoc to these two tests

2016-12-11 02:06 UTC, JoeSun940303 commented on k-distribution/tutorial/1_k/4_imp++/lesson_4/imp.k
> +                > Stmt Stmt                  [left]
Sorry about this, when we tried to fix this bug, we add some spaces to the files but it hard for us to reformat it to the former version. The real change is labeled in dark green in the comparison and all other thing are kept the same.

2016-12-11 02:11 UTC, JoeSun940303 commented on k-distribution/src/test/resources/convertor-tests/PrintFlushTest.k
> +module IMP
This, this is copied from k-distribution/tutorial/1_k/4_imp++/lesson_4/imp.k, the reason we add this file is that if we want to read .k file by using KoreUtils to test it, seems the file should only be placed in resources folder.

2016-12-14 20:42 UTC, cos commented on k-distribution/tutorial/1_k/4_imp++/lesson_4/imp.k
> +                > Stmt Stmt                  [left]
I suggest you redo the changes and on a fresh fork of master. I know how github formatting works, but that doesn't help with breaking the change history. Thanks!

2016-12-14 20:43 UTC, cos commented on k-distribution/src/test/resources/convertor-tests/PrintFlushTest.k
> +module IMP
In this case, you should minimize the file to whatever is needed to test the fix.

2017-02-06 03:29 UTC, daejunpark commented
Close this PR exercise in the class.

2017-02-06 03:29 UTC, closed without merging