Revise error message for deprecated(old) style of k definitions.
kframework/k-legacy pull request #2235
Opened 2016-11-28 22:10 UTC by hreada

Revising the error message when parsing a K definition that uses old fashion of ' \' ' instead of parenthesis. The new error message looks the following.

[Error] Compiler: Had 2 parsing errors.
[Error] Inner Parser: Parse error: unexpected character '*'.Please use '(' or
')' instead of '`'
        Source(./test.k)
        Location(10,29,10,30)
[Error] Inner Parser: Parse error: unexpected character '*'.Please use '(' or
')' instead of '`'
        Source(./test.k)
        Location(11,24,11,25)

2016-11-29 12:48 UTC, radumereuta commented on kernel/src/main/java/org/kframework/parser/concrete2kore/kernel/Parser.java
> +            if (content.toString().indexOf('`')>=0) msg += "Please use '(' or ')' instead of '`'";
This can actually fail badly, and the error message can be misleading in some cases.
If the language actually includes a terminal backtick, and the user has a proper error at that location, now K would suggest using parenthesis instead of actually fixing the problem.

2016-11-29 12:59 UTC, radumereuta commented
The backtick modifications started after this issue was reported: #1970 and #2028.
I think for #1948 we should just manually fix the backticks and continue debugging from there.

Also, when doing pull request, try to keep the original alignment, because it makes code reviews a lot harder.

2016-12-01 01:01 UTC, hreada commented
@radumereuta I changed backtick to parenthesis and everything works fine under the latest version of K. So what is the real problem here?

2016-12-01 03:51 UTC, cos commented
I agree with @radumereuta. The backticks haven't been in use long enough to warrant a special error message. The alternate "fix" for this is to go through the existing definitions and check whether there are any leftover backticks. If there are none -- likely -- great. If there are some, we should simply replace them with parenthesis.

2016-12-09 16:59 UTC, cos requested changes

2016-12-09 16:59 UTC, cos commented on kernel/src/main/java/org/kframework/parser/concrete2kore/kernel/Parser.java
> +                            stateReturn.key.stateEnd)).function);
please do not reformat the files.

2016-12-09 16:59 UTC, cos commented on kernel/src/main/java/org/kframework/parser/concrete2kore/kernel/Parser.java
> +            if (content.toString().indexOf('`')>=0) msg += "Please use '(' or ')' instead of '`'";
maybe rephrase as: "Using backtick, '`', for K brackets is deprecated. If you are using it for this purpose, please use regular parenthesis, '(' and ')', instead."

2017-02-06 03:29 UTC, daejunpark commented
Close this PR exercise in the class.

2017-02-06 03:29 UTC, closed without merging