Fixed bug 2097 - Parsing error
kframework/k-legacy pull request #2240
Opened 2016-11-30 05:19 UTC by xianzezhan

Fixed #2097 

The problem is there is a parsing error for .TaskCellBag. After treating it as .Bag, now --pattern option prints out the correct solution.

2016-12-01 16:18 UTC, cos commented
Special-casing for this input pattern is not a real fix for this problem. Let's discuss on the issue thread to figure out the bug.

2016-12-09 17:19 UTC, cos requested changes

2016-12-09 17:19 UTC, cos commented on kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
> +            if(b.contents().equals("<tasks> .TaskCellBag </tasks>"))
special-casing for this particular String "<tasks> .TaskCellBag </tasks>" is not a fix, regardless of where the check is made.

2017-02-06 03:28 UTC, daejunpark commented
Close this PR exercise in the class.

2017-02-06 03:28 UTC, closed without merging