Fix bug #1942 Rename/split Bag to Cells
kframework/k-legacy pull request #2242
Opened 2016-12-01 19:00 UTC by chmx0929

To distinguish data structure "Bag" and the syntax "Bag". We rename the sort name "Bag", defined in module KCELLS in kast.k, to CellBag. Then, we fix corresponding errors. For all tests that use module KCELLS in kast.k, especially tests in RuleGrammarTest.java, are perfect tests to check whether the program still works after we do this change.

2016-12-05 09:42 UTC, radumereuta requested changes
This change actually impacts every definition we have in K right now, since this file is imported and used in definitions to parse rules and configuration cells. So all tests should pass. I don't know why codeship didn't start testing this PR.

2016-12-05 09:42 UTC, radumereuta commented on kernel/src/main/java/org/kframework/kore/compile/checks/CheckSortTopUniqueness.java
> +        //Term Bag here stands for syntax Bag, so we rename it to CellBag to distinguish data structure Bag and syntax Bag
Comments in the file should reflect what is in the file. This comment should be in something like a changelog.

2016-12-05 09:42 UTC, radumereuta commented on kernel/src/main/java/org/kframework/parser/concrete2kore/generator/RuleGrammarGenerator.java
> +                                    //Term Bag here stands for syntax Bag, so we rename it to CellBag to distinguish data structure Bag and syntax Bag
Same as above.

2016-12-05 09:42 UTC, radumereuta commented on kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java
> +    // if we rename syntax Bag to CellBag.
Same as above.

2016-12-09 03:35 UTC, HelenRouty commented
Thank you. Where should we create a change log? Is the change log pull request?

2016-12-09 04:00 UTC, HelenRouty commented
## Change Log
We changed 4 "Bag" to "CellBag":
(1) check method in _kernel/src/main/java/org/kframework/kore/compile/checks/CheckSortTopUniqueness.java_
(2) processHybridModule method in _kernel/src/main/java/org/kframework/parser/concrete2kore/generator/RuleGrammarGenerator.java_
(3) syntax in _k-distribution/include/builtin/kast.k_
(4) test cases in _kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java_

## Tests
Tests in the file _k/kernel/src/test/java/org/kframework/parser/concrete2kore/RuleGrammarTest.java_ test rule grammar. And they are perfect tests to test whether the program works
if we rename syntax Bag to CellBag.

2016-12-10 15:53 UTC, cos commented
@radumereuta, could you have a quick look at this?

2016-12-15 14:10 UTC, radumereuta commented
The changes look right, but I don't see the tests passing, or even starting.
@cos do you know anything about that?

2017-02-06 03:28 UTC, daejunpark commented
Close this PR exercise in the class.

2017-02-06 03:28 UTC, closed without merging