Bugfix2219
kframework/k-legacy pull request #2243
Opened 2016-12-02 04:56 UTC by HelenRouty

The bug is: when using --no-prelude to generate compiledDefinition for an empty module, there will be a NoSuchElementException. The is due to a lack of checks for the Optional (Java) or Option(scala) types before extracting values from them. To fix the bug, we created an empty-module for unit test and added checks for Optional and Options.  After adding checks, we were able to create a CompiledDefinition with its topCellInitializer of null value.

To further avoid Exceptions when running Krun program caused by having no cells in compiledDefinition, we passed the noPrelude flag from kRunOption.output to CompiledDefinition. Then we disabled definition parsing and rename anonymous variables when generating K program result for the empty-module. Meanwhile, we added more checks to avoid exceptions for null value K and null KApply's klable value.

Finally, we added test cases for non-empty module without --no-prelude parameter for regression test. We also added more test cases for kast program, KAST and BINARY pretty print modes.

2016-12-09 17:35 UTC, cos requested changes
This is nice work and shows a good understanding of the problem. Still, I think there is a way to handle this without propagating null checks all over the codebase. Instead of allowing `null`, use a new, made up, placeholder term. For the sort, see the comment below.

2016-12-09 17:35 UTC, cos commented on .idea/codeStyleSettings.xml
> -
please don't delete this file

2016-12-09 17:35 UTC, cos commented on kernel/src/main/java/org/kframework/kompile/DefinitionParsing.java
> +                throw new AssertionError("Wrong KLabel for rule content");
please don't reformat the file

2016-12-09 17:35 UTC, cos commented on kore/src/main/scala/org/kframework/compile/ConfigurationInfoFromModule.scala
> +      null
you could return the `K` sort here instead.

2016-12-09 18:53 UTC, HelenRouty commented
@cos  Thank you for your suggestions. Do you mean that we can create a placeholder Sort: 
E.g. `val KNull  = Sort("KNull")` as a built-in Sort in Sorts.java and use Sorts.KNull to replace all null value check for Sort? 
Should we have null value placeholders for KLable and KApply as well?

2016-12-10 15:43 UTC, cos commented
You can use the top sort, i.e., `K` as a "null" sort. For terms, yes, I'm suggesting to add a KLabel, named something like "<empty>", and make a term of arity 0 from it, i.e., `KApply(KLabel("<empty>"), List())` .

2016-12-10 22:51 UTC, HelenRouty commented
@cos Thank you. So we should use Sorts.K to replace null sort right?

2016-12-11 02:06 UTC, cos commented
> So we should use Sorts.K to replace "null" sort right?

Yes.

> Could we use the KORE.KLabel("") for "null" KLabel?

No, use something like "<empty>", obtained by adding a production to the definition.

2016-12-11 03:31 UTC, HelenRouty commented
Hi @cos. Thank you for providing more details. However, I still have a hard time to understand what type of KLabel should be used. Could we schedule an appointment with you at any time on Dec.12(Mon) after 5:00pm or any time after Dec.12?

2016-12-12 20:19 UTC, cos commented
We can meet today at 5pm if you like.

2016-12-12 22:39 UTC, HelenRouty commented
@cos Thank you. Where can I find you?

2016-12-14 04:13 UTC, HelenRouty commented
Thanks to @cos explanation, we found that we misunderstood the root cause of this bug. A better description and fix is in this newer pull request: [https://github.com/kframework/k/pull/2249](https://github.com/kframework/k/pull/2249).

2016-12-14 04:13 UTC, closed without merging