fix issue 2215
kframework/k-legacy pull request #2246
Opened 2016-12-09 04:29 UTC by hksskh

fix the issue 2215 by adding boolean variable to iteratively record if there is any cell that is not leaf cell among all child cells of current cell. major modification in function genInternal in class GenerateSentencesFromConfigDecl.
pass the ConfigurationInheritanceTest mentioned in issue 1918 by @bmmoore, and also pass other tests.
stil fail in one assertion:
in class GenerateSentencesFromConfigDecl, function computeSentencesOfWellFormedCell, line 274, the "assert isLeaf" fails. Don't quite understand why this assertion exists. simply comment this assertion and pass all other tests.

2016-12-09 19:10 UTC, cos requested changes

2016-12-09 19:10 UTC, cos commented on kernel/src/main/java/org/kframework/kore/compile/GenerateSentencesFromConfigDecl.java
> +            isLeaf = true;
the `maincell` is contains a KSequence(`~>`), which is not part of the configuration, thus the cell should be a leaf.

2016-12-09 19:10 UTC, cos commented on kernel/src/main/java/org/kframework/kore/compile/GenerateSentencesFromConfigDecl.java
> +    private static Tuple4<Set<Sentence>, List<Sort>, K, Boolean> genInternal(K term, K ensures, Att cfgAtt, Module m) {
what does the `Boolean` encode? maybe explain in the javadoc above

2016-12-10 00:12 UTC, hksskh commented
add new commit, please review it, thanks. @cos

2017-02-06 03:28 UTC, daejunpark commented
Close this PR exercise in the class.

2017-02-06 03:28 UTC, closed without merging