ARRAY module in UIUC K
kframework/k-legacy pull request #2349
Opened 2017-10-20 20:30 UTC by dwightguth

2017-10-25 04:12 UTC, ehildenb commented
Please add tests.

2017-11-03 19:37 UTC, ehildenb commented
What should the semantics of `makeArray(5, 0)[7]` be? That is, should it return the default value `0`, or some error term because `7` it outside the bounds of the array?

2017-11-03 19:56 UTC, dwightguth commented
`makeArray(5, 0)[7]` and `makeArray(5, 0)[7 <- 1][7]` should both be zero. The idea behind ARRAY is that an efficient implementation backs an array as an actual array with a fixed length, so any element not explicitly assigned or outside the length of the array is always equal to the default value.

2017-11-14 22:15 UTC, bmmoore requested changes
The array code looks good.

My only complaint is that the PR also moves the crypto tests into their own `tests/builtins/crypto` directory. That's a good change, but entirely unrelated to arrays and also unmentioned in the commit messages. Perhaps it belongs in #2350 instead? If you don't mind I can move that change into that PR instead and approve this.

2017-11-14 22:15 UTC, bmmoore commented on k-distribution/include/builtin/domains.k
> +  syntax Array ::= array(Map, Int, K)
Is there any way to stop this from being directly called to create a value with keys set outside the expected range?

2017-11-14 22:30 UTC, bmmoore approved these changes

2017-11-14 22:33 UTC, bmmoore commented
As @dwightguth pointed out I missed that we only support one test definition per directory, so making a subdirectory for the tests previously directly in `test/builtins` is a good idea before making `test/builtins/array`.

2017-11-14 22:33 UTC, merged